# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
