# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_bug_image'),
        ('reporter', '0002_auto_20170424_0712'),
    ]

    operations = [
    ]
