# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_merge_20170425_0932'),
        ('reporter', '0003_merge_20170424_0936'),
    ]

    operations = [
    ]
